# Build the C++ code
name: Check build

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

jobs:

  check_build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Remove g++
        run: sudo apt-get remove g++

      - name: g++ must be removed. It is :-)
        run: g++ --version || true

      - name: Remove llvm
        run: sudo apt-get remove llvm llvm-*

      - name: Remove clang
        run: sudo apt-get remove clang clang-*

      #- name: Find llvm
      #  run: apt search llvm

      #- name: Find clang
      #  run: apt search clang

      - name: clang++ must be removed. It is :-)
        run: clang++ --version || true

      # Install Intel
      - uses: rscohn2/setup-oneapi@v0
        with:
          list: true
          components: |
            icx

      - name: Show the common variables script
        run: cat /opt/intel/oneapi/setvars.sh

      - name: Compile
        run: |
          source /opt/intel/oneapi/setvars.sh
          icpx main.cpp --verbose -o gha_intel_cpp17
      
      - name: Run the program
        run: ./gha_intel_cpp17





